services:
  - type: web
    name: randomaccess-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: 
        value: mysql://avnadmin:<TU_PASSWORD>@<HOST>:<PUERTO>/<BASE_DE_DATOS>
