# Generated by Django 4.2.13 on 2025-06-19 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('LIKE', 'Like'), ('LOVE', 'Love'), ('NOJAO', 'Nojao'), ('TITE', 'Tite'), ('WAO', 'Wao'), ('XDDD', 'Xddd')], max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomaccess.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomaccess.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomaccess.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomaccess.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomaccess.user')),
            ],
        ),
    ]
